doi-for-citation-count: 10.7326/0003-4819-158-3-201302050-00583
doi: 10.1234/equator/1010101
id: spirit
translations: []
title: The SPIRIT reporting guideline for writing a protocol for a clinical trial
acronym: SPIRIT
acronym-definition: "Standard Protocol Items: Recommendations for Interventional Trials"
open-e-and-e: true
journal-endorsement-count: 1000+
version: 'SPIRIT 2013 v1.1'
articles:
  development:
    id: chanSPIRIT2013Statement2013a
    abstract: >-
      The protocol of a clinical trial serves as the foundation for study
      planning, conduct, reporting, and appraisal. However, trial protocols and
      existing protocol guidelines vary greatly in content and quality. This
      article describes the systematic development and scope of SPIRIT (Standard
      Protocol Items: Recommendations for Interventional Trials) 2013, a guideline
      for the minimum content of a clinical trial protocol.The 33-item SPIRIT
      checklist applies to protocols for all clinical trials and focuses on
      content rather than format. The checklist recommends a full description of
      what is planned; it does not prescribe how to design or conduct a trial. By
      providing guidance for key content, the SPIRIT recommendations aim to
      facilitate the drafting of high-quality protocols. Adherence to SPIRIT would
      also enhance the transparency and completeness of trial protocols for the
      benefit of investigators, trial participants, patients, sponsors, funders,
      research ethics committees or institutional review boards, peer reviewers,
      journals, trial registries, policymakers, regulators, and other key
      stakeholders.
    accessed:
      - year: 2025
        month: 2
        day: 18
    author:
      - family: Chan
        given: An-Wen
      - family: Tetzlaff
        given: Jennifer M.
      - family: Altman
        given: Douglas G.
      - family: Laupacis
        given: Andreas
      - family: Gøtzsche
        given: Peter C.
      - family: Krleža-Jerić
        given: Karmela
      - family: Hróbjartsson
        given: Asbjørn
      - family: Mann
        given: Howard
      - family: Dickersin
        given: Kay
      - family: Berlin
        given: Jesse A.
      - family: Doré
        given: Caroline J.
      - family: Parulekar
        given: Wendy R.
      - family: Summerskill
        given: William S.M.
      - family: Groves
        given: Trish
      - family: Schulz
        given: Kenneth F.
      - family: Sox
        given: Harold C.
      - family: Rockhold
        given: Frank W.
      - family: Rennie
        given: Drummond
      - family: Moher
        given: David
    citation-key: chanSPIRIT2013Statement2013a
    container-title: Annals of Internal Medicine
    container-title-short: Ann Intern Med
    DOI: 10.7326/0003-4819-158-3-201302050-00583
    ISSN: 0003-4819
    issue: '3'
    issued:
      - year: 2013
        month: 2
        day: 5
    page: 200-207
    publisher: American College of Physicians
    source: acpjournals.org (Atypon)
    title: 'SPIRIT 2013 Statement: Defining Standard Protocol Items for Clinical Trials'
    title-short: SPIRIT 2013 Statement
    type: article-journal
    URL: https://www.acpjournals.org/doi/full/10.7326/0003-4819-158-3-201302050-00583
    volume: '158'
authors:
  - family: Chan
    given: An-Wen
  - family: Tetzlaff
    given: Jennifer M.
  - family: Altman
    given: Douglas G.
  - family: Laupacis
    given: Andreas
  - family: Gøtzsche
    given: Peter C.
  - family: Krleža-Jerić
    given: Karmela
  - family: Hróbjartsson
    given: Asbjørn
  - family: Mann
    given: Howard
  - family: Dickersin
    given: Kay
  - family: Berlin
    given: Jesse A.
  - family: Doré
    given: Caroline J.
  - family: Parulekar
    given: Wendy R.
  - family: Summerskill
    given: William S.M.
  - family: Groves
    given: Trish
  - family: Schulz
    given: Kenneth F.
  - family: Sox
    given: Harold C.
  - family: Rockhold
    given: Frank W.
  - family: Rennie
    given: Drummond
  - family: Moher
    given: David