---
title: "Discussion for SRQR item: [Synthesis and interpretation](..)"
citation: false
---
::: {.grid id="synthesis-and-interpretation"}
::: {.g-col-9}
#### Synthesis and interpretation
:::
::: {.g-col-3}
:::
:::

Describe the main <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem15" aria-controls="offcanvasExample" role="button">analytic findings</span>.^[The nature of these findings and how they are reported will depend on the approach and methodology selected and thus should be in alignment with the approach and methods.]

In most cases, report a synthesis of the data along with specific quotes, examples, or illustrations derived from the data.

<!-- #ASK: is this same as links to empirical data? -->

["I like when authors use words like 'many', 'few', or 'all' to describe frequency."[Nkinda Akaro - Researcher]{.attribution}]{.aside}

Consider describing frequency, variety, representativeness, counter-examples, concrete details, contextualization, conditions, and qualifications related to the findings.

Frequency counts play a limited role in qualitative research, and need not be reported unless they play a meaningful role in interpretation of the data.

If your findings include integration with prior literature or theory and/or the development of a theory, model or meta-narrative, consider using tables and figures to communicate these findings.

Items 16 and 18 can be reported in Results or Discussion sections.^[In qualitative research the distinction between results and discussion tends to blur because analysis often involves interpretation, inference, and synthesis. Although most journals require separate sections for Results and Discussion, many elements of Items 16 and 18 could reasonably be reported in either section. As such, we defer to authors and editors to determine where to report these essential elements.]

::: {#synthesis-and-interpretation-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Examples

Jump to:

* [Why readers need this information](#sec-synthesis-and-interpretation-2)
* [Examples](#sec-synthesis-and-interpretation-3)


## Why readers need this information{#sec-synthesis-and-interpretation-2}

This information helps readers know what decisions the researchers made and why so the reader can 1) consider the relevance to their context and the resonance with their own experience or observations (or lack of resonance and why that might be) and 2) evaluate or critically appraise the manuscript.

<!-- #ASK doesn't seem to fit -->

## Examples{#sec-synthesis-and-interpretation-3}

> We identified four patterns of NVB (non-verbal behavior) that relate to handover quality and have dubbed them: (1) joint focus of attention; (2) ‘the poker hand’; (3) parallel play; and (4) kerbside consultation. Each pattern constitutes a ‘transfix,’ or systematic way of participating non-verbally in the care transfer process. And, although there are variations in each pattern, we have been able to code virtually every handover we have observed in nursing, medicine and surgery into one of these four categories.

> Because our participants came from similar educational backgrounds, had studied medicine as their tertiary course, were embedded in the culture of medicine, and were associated in meaningful ways with a single medical school, we approached their transcripts with the assumption that they belonged to a loosely formed discourse community. Although their graduation dates ranged over a period of 50 years and their collective sphere of practice included 10 different specialty areas, there were many similarities in their experiences of enculturation during and after medical school.

> Their three major (often overlapping) areas of concern were epistemic (acquiring knowledge and skill), interpersonal (relating to patients, families, colleagues and administrators) and personal (achieving work–life balance). In each of these areas, medical enculturation was achieved by two overlapping processes, ‘absorption’ and ‘assimilation’, each of which may have distinct implications for postgraduate medical education.

[Back to top](#synthesis-and-interpretation)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Synthesis and interpretation"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
