---
editor:
  markdown:
    wrap: none
---

+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [STROBE](reporting-guidelines/strobe)                                                                                                                                             | **Observational Epidemiology**, including:                                                                                                                                                                                    |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
|                                                                                                                                                                                   | -   [Cohort studies]{.defined data-bs-toggle="offcanvas" href="#glossaryItemcohort_studies" aria-controls="glossaryItemcohort_studies" role="button"} (e.g., longitudinal, prospective, and retrospective studies)            |
|                                                                                                                                                                                   | -   [Case-control studies]{.defined data-bs-toggle="offcanvas" href="#glossaryItemcase_control_studies" aria-controls="glossaryItemcase_control_studies" role="button"} (e.g., case-referent studies)                         |
|                                                                                                                                                                                   | -   [Cross-sectional studies]{.defined data-bs-toggle="offcanvas" href="#glossaryItemcross_sectional_studies" aria-controls="glossaryItemcross_sectional_studies" role="button"} (e.g., transverse and prevalence studies)    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>                                                                                                                                                                              | **Systematic reviews**                                                                                                                                                                                                        |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [PRISMA](reporting-guidelines/prisma)                                                                                                                                             | [Systematic reviews]{.defined data-bs-toggle="offcanvas" href="#glossaryItemsystematic_reviews" aria-controls="glossaryItemsystematic_reviews" role="button"} of trials                                                       |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [PRISMA-P](reporting-guidelines/prisma-protocols/)                                                                                                                                | Systematic review protocols                                                                                                                                                                                                   |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [MOOSE](reporting-guidelines/meta-analysis-of-observational-studies-in-epidemiology-a-proposal-for-reporting-meta-analysis-of-observational-studies-in-epidemiology-moose-group/) | [Meta-analyses]{.defined data-bs-toggle="offcanvas" href="#glossaryItemmeta_analyses" aria-controls="glossaryItemmeta_analyses" role="button"} of Observational studies                                                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| <br>                                                                                                                                                                              | **Randomized trials**                                                                                                                                                                                                         |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [CONSORT](reporting-guidelines/consort)                                                                                                                                           | [Randomized trials]{.defined data-bs-toggle="offcanvas" href="#glossaryItemrandomised_trials" aria-controls="glossaryItemrandomised_trials" role="button"} (clinical trials, or experimental studies of health interventions) |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| <br>                                                                                                                                                                              | Protocols for randomized trials                                                                                                                                                                                               |
|                                                                                                                                                                                   |                                                                                                                                                                                                                               |
| [SPIRIT](reporting-guidelines/spirit-2013-statement-defining-standard-protocol-items-for-clinical-trials/)                                                                        |                                                                                                                                                                                                                               |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [SRQR](reporting-guidelines/srqr)                                                                                                                                                 | [Qualitative Research]{.defined data-bs-toggle="offcanvas" href="#glossaryItemqualitative_research" aria-controls="glossaryItemqualitative_research" role="button"}                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [CARE](reporting-guidelines/care)                                                                                                                                                 | [Case Reports]{.defined data-bs-toggle="offcanvas" href="#glossaryItemcase_reports" aria-controls="glossaryItemcase_reports" role="button"}                                                                                   |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [STARD](reporting-guidelines/stard)                                                                                                                                               | [Diagnostic Test Accuracy Studies]{.defined data-bs-toggle="offcanvas" href="#glossaryItemdiagnostic_test_accuracy_studies" aria-controls="glossaryItemdiagnostic_test_accuracy_studies" role="button"}                       |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [TRIPOD + AI](reporting-guidelines/tripod-statement/)                                                                                                                             | [Prediction Models]{.defined data-bs-toggle="offcanvas" href="#glossaryItemprediction_models" aria-controls="glossaryItemprediction_models" role="button"}                                                                    |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [ARRIVE](reporting-guidelines/arrive)                                                                                                                                             | [Animal Research]{.defined data-bs-toggle="offcanvas" href="#glossaryItemanimal_research" aria-controls="glossaryItemanimal_research" role="button"}                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [SQUIRE](reporting-guidelines/squire)                                                                                                                                             | [Quality Improvement in Healthcare]{.defined data-bs-toggle="offcanvas" href="#glossaryItemqi" aria-controls="glossaryItemqi" role="button"}                                                                                  |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| [CHEERS](reporting-guidelines/cheers/)                                                                                                                                            | [Economic Evaluations]{.defined data-bs-toggle="offcanvas" href="#glossaryItemeconomic_evaluations" aria-controls="glossaryItemeconomic_evaluations" role="button"}                                                           |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

: {tbl-colwidths="\[25,75\]"}