---
title: "The ABCDE guidelines for writing-up<br>XYZ"
subtitle: "Ea ea velit dolore exercitation reprehenderit reprehenderit aute elit eu proident voluptate commodo adipisicing."
container-author: John Smith
keywords: "CONSORT guidelines guidance writing how to write draft edit"
license: CC BY
pagetitle: "The ABCDE guidelines for reporting"
title-prefix: ABCDE
description-meta: "Description for search engines and social media"
author-meta: "Authors information for search engines and social media"
title-block-banner: true
smooth-scroll: true
lang: en-GB
css: 
  - styles.css
  - index.css
from: markdown+raw_html+markdown_in_html_blocks
link-external-icon: true
citation:
  type: webpage
  title: The ABCDE guidelines for reporting XYZ - version 1.0
  container-title: EQUATOR website guidelines something
  container-author: Gary Collins
  author: 
    - Author One
    - Author Two
    - Author Three
  volume: 21
  issue: 2
  isbn: 978-3-8474-1017-1
  keyword: word, another
  issued: 2022-10
  issn: 1539-9087
  doi: 10.1145/3514174
google-scholar: true
---

## Resources

::: {.grid}

::: {.g-col-md-4}
<button type="button" class="btn btn-primary btn-lg width-100">Template</button>
For drafting research manuscripts
:::

::: {.g-col-md-4}
<button type="button" class="btn btn-primary btn-lg width-100">Checklist</button>
For checking and demonstrating compliance
:::

::: {.g-col-md-4}
<button type="button" class="btn btn-primary btn-lg width-100">Deserunt</button>
For ipsum exercitation
:::

:::

::: {.citations-counter}
<span class="__dimensions_badge_embed__" data-doi="10.1001/jama.2016.9797" data-legend="never" data-style="large_rectangle"></span><script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
:::

## When to use this guidance

::: {.callout-tip icon=false appearance="simple"}
Use this guidance for:

* Est qui <abbr title='Here is a definition. Just a short sentence or two.'>exercitation</abbr> est commodo irure
* Culpa ipsum exercitation culpa ea deserunt.

It can also be used for:

* Enim quis laborum dolor occaecat fugiat (use items #-#).
* Quis nostrud incididunt ipsum nisi eu laboris (use items #-#).
:::

::: {.callout-warning icon=false appearance="simple"}
**Do not** use this guidance for:

* writing incididunt ipsum nisi, use [BHUJSD-Cudhjs]() instead
* writing incididunt ipsum nisi, use [THUYGH]() instead
* writing incididunt ipsum nisi
* appraising quality, consider using [QWETY](https://www.google.com) instead
:::

::: {.callout-note icon=false appearance="simple"}
For **designing** research consider:

* [resource](https://www.google.com)
* [resource](https://www.google.com)

For **appraising** research consider:

* [resource](https://www.google.com)
* [resource](https://www.google.com)
:::

## Guidance

<small>Approx. 7 min read</small>

```{python}
#| echo: false
#| output: asis


IPSUM = "Pariatur occaecat commodo sint ea laborum voluptate ut veniam voluptate Fugiat voluptate qui minim sunt esse non et Ea pariatur nisi et irure magna ad commodo nostrud laboris elit cupidatat Aute Lorem eiusmod eu eiusmod laborum consequat tempor sint consequat id tempor Dolore sit labore dolore proident consectetur ex ipsum deserunt adipisicing ea aliquip commodo anim dolor".split()

SECTIONS = ['Introduction', 'Methods', 'Results', 'Discussion']
TEMPLATE = \
"""
#### {idx}. {title}

Describe <span class="defined" data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample" role="button">irure sint ipsum aute eiusmod</span> irure laborum sunt minim. Irure aliquip do dolor do ea ipsum nostrud ea <abbr title='Here is a definition. Just a short sentence or two.'>exercitation elit Lorem ullamco</abbr> proident reprehenderit. Ipsum consequat nisi ullamco consectetur anim voluptate. 

If you **did not** do irure sint ipsum aute eiusmod irure laborum sunt minim. Irure aliquip do dolor do ea ipsum nostrud ea.

If [applicability criteria not met], describe nisi ullamco consectetur anim.

**Save words:** Ex anim do quis magna nisi sit ipsum commodo minim.

::: {{.callout-note appearance="minimal" collapse=true}}

## Read more

Jump to:

* [Examples](#sec-1-{idx})
* [Why readers need this information](#sec-2-{idx})
* [Design and appraisal resources](#sec-3-{idx})

## Examples {{#sec-1-{idx}}}

✅&nbsp;&nbsp;**Good reporting**

> Et fugiat velit consequat sunt officia sit veniam officia. Exercitation est nisi ex deserunt laboris reprehenderit ut sit nisi. Veniam culpa quis pariatur id consectetur labore aliquip ut exercitation duis velit. Sunt laborum anim do proident proident qui enim veniam aliquip qui occaecat occaecat. 

This example is good because...

> Eu cillum dolore aliquip voluptate et aliquip minim aute. Deserunt eu.

This example is good because...

❌&nbsp;&nbsp;**Bad reporting**

> Et fugiat velit consequat sunt officia sit veniam officia. Exercitation est nisi ex deserunt laboris reprehenderit.

This example is bad because it is missing X, Y, Z.

> Eu cillum dolore ullamco.

## Why readers need this information {{#sec-2-{idx}}}

Et fugiat velit consequat sunt officia sit veniam officia. Exercitation est nisi ex deserunt laboris reprehenderit ut sit nisi. Veniam culpa quis pariatur id <span class="defined" data-bs-toggle="offcanvas" href="#offcanvasExample" aria-controls="offcanvasExample" role="button">consectetur labore</span> aliquip ut exercitation duis velit. Sunt laborum anim do proident proident qui enim veniam aliquip qui occaecat occaecat. Eu cillum dolore aliquip voluptate et aliquip minim aute. Deserunt eu amet occaecat adipisicing sint cupidatat duis excepteur et aliqua excepteur. Do enim exercitation culpa enim in velit ullamco.

## Design advice and extra resouces {{#sec-3-{idx}}}

Design advice:

* [resource]()
* [resource]()

How to do this item: 

* [resource]()
* [resource]()

Training: [Link to training]()

:::

"""
NUMITEMS = 5
for sec_idx, section in enumerate(SECTIONS):
    print("### "+section+"\n\n")
    for i in range(NUMITEMS):
        idx = i + 1
        idx = sec_idx * NUMITEMS + idx
        print(TEMPLATE.format(idx=idx, title=' '.join(IPSUM[idx:idx+2]).capitalize()))
```

## FAQs

### How this guidance was made

Excepteur deserunt mollit enim fugiat reprehenderit. Fugiat veniam sunt nulla ullamco. Nisi nulla quis cillum occaecat reprehenderit amet exercitation proident. Et et et proident magna fugiat velit do occaecat in nulla. Deserunt adipisicing veniam id ex anim enim mollit proident ad duis magna. Ipsum officia laborum ad eiusmod culpa ullamco. Fugiat incididunt incididunt ex quis labore consectetur velit officia cupidatat aute quis ex incididunt.

### Pariatur proident minim

Incididunt voluptate fugiat aliqua esse. Esse ex voluptate anim aliqua voluptate consectetur minim. Nostrud nisi culpa magna quis Lorem do pariatur esse do ipsum amet velit. Excepteur cillum pariatur Lorem consequat et reprehenderit esse magna fugiat enim. Laboris magna et deserunt pariatur cupidatat culpa eu elit. Cillum consequat non nisi eu. Occaecat proident incididunt proident ea voluptate. Ex velit qui eu cillum.

### Laborum quis ad

Id quis irure eu officia qui. Qui occaecat anim enim nisi ullamco in do veniam incididunt culpa deserunt fugiat. Ut excepteur consectetur fugiat occaecat sit. Qui irure adipisicing sint nisi minim consectetur commodo. Mollit ad ad ipsum quis exercitation anim anim. Commodo aliquip irure ad consectetur.





<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
<div class="offcanvas-header">
<h5 class="offcanvas-title" id="offcanvasExampleLabel">Irure sint ipsum aute eiusmod</h5>
<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
</div>
<div class="offcanvas-body">
<div>
Qui duis consequat nisi anim ullamco officia dolore ut sunt. Consequat ad elit ex fugiat in eiusmod incididunt elit id ullamco. Quis ut minim et elit adipisicing ad cupidatat. Cupidatat dolore voluptate do qui consectetur adipisicing nulla. Ad pariatur nostrud culpa culpa nulla ex dolore elit ullamco exercitation occaecat occaecat ipsum. Lorem tempor elit ullamco amet id irure mollit ullamco eiusmod et nisi consequat qui pariatur. Enim qui adipisicing cupidatat consectetur amet deserunt proident duis occaecat esse fugiat enim.

[Learn more](https:www.google.com)
</div>
</div>
</div>



