---
title: Privacy Policy
---

## About the EQUATOR Network

The EQUATOR (Enhancing the QUAlity and Transparency Of health Research) Network is an international initiative that seeks to improve the reliability and value of published health research literature by promoting transparent and accurate reporting and wider use of robust reporting guidelines.

This website is operated by the University of Oxford. We are committed to protecting the privacy and security of your personal information (‘personal data’).

This policy (together with our [Terms of Use](terms-of-use.qmd)) describes how we collect and use your personal data during your use of our site, in accordance with the General Data Protection Regulation (GDPR) and associated data protection legislation. Where we refer in this policy to your ‘personal data’, we mean any recorded information that is about you and from which you can be identified. It does not include data where your identity has been removed (anonymous data).

## Who is using your personal data?

The University of Oxford is the “data controller” for the information that you provide to us when visiting this website. This means that we decide how to use it and are responsible for looking after it in accordance with the GDPR.

Access to your personal data within the University will be provided to those staff who need to view it as part of their work in connection with the operation of this website. It will also be shared with the third parties described below. By visiting our site, you are accepting and consenting to the practices described in this policy.

## Types of data we collect about you

We may collect, use, store and transfer the following kinds of personal data about you, when you submit it to us:

* Email communications: If you get in touch with us by sending an enquiry to one of the email addresses listed on our website. We will record your first name, last name, email address, organisation, and any message you send.
* Marketing and Communications Data: If you sign up to receive the EQUATOR Newsletter, we will collect your first name, last name and email address. We may also automatically collect technical information about how you interact with the EQUATOR newsletter to help us improve our newsletter.
* Website analytics: We use Google Analytics to track and analyse web traffic in order for us to improve our website. Information processed for this purpose includes, but is not limited to, IP addresses.

## When we collect your data

We will collect the vast majority of data about you when you use our site, correspond with us, subscribe to the EQUATOR Newsletter or other social media functions on our site.

When you visit our site, we may also automatically collect technical information about your visit from your computer. You can find out more information about this below.

## How we use your data

We process your data for one or more of the following reasons:

* To provide you with the newsletter services you have requested e.g. Users actively subscribe to our EQUATOR Newsletter, or the Librarian Network. This processing is necessary to meet our contractual obligations to you or to take steps requested by you prior to entering into a contract. Information processed for this purpose includes, your name and email address. We do this only where you have specifically indicated that you consent to receive such communications, for example, registering your name and email address and confirming subscription. You can withdraw your consent at any time by clicking unsubscribe in the email footer. In this event, we will stop any processing as soon as we can. However, this will not affect the lawfulness of any processing carried out before your withdrawal of consent and you may no longer be able to use the site in the same way you did before. We will not provide your data to other businesses so they can use it for marketing purposes.
* For purposes arising from your use of this website, for example, to ensure that we understand who uses our site and how our site is used and to improve our site and ensure it is secure. This processing occurs because it is necessary to meet our legitimate interests in operating this website. Information processed for this purpose includes, but is not limited to, IP addresses. We will only use your data for the purposes for which we collected it, unless we reasonably consider that we need to use it for another related reason and that reason is compatible with the original purpose. If we need to use your data for an unrelated purpose, we will seek your consent to use it for that new purpose.

Please note that we may process your data without your knowledge or consent, in compliance with the above rules, where this is required or permitted by law.

## Sharing your data with third parties

We may share your data with third parties who provide services on our behalf, such as for administrative purposes and website hosting. All our third-party service providers are required to take appropriate security measures to protect your data in line with our policies. We do not allow them to use your data for their own purposes. We permit them to process your data only for specified purposes and in accordance with our instructions.

Where your data is shared with third parties, we will seek to share the minimum amount necessary.

## Where we store or use your data

We store data collected by the website electronically. The data is stored on secure servers at University of Oxford.

There may be occasions when we transfer your data outside the European Economic Area (EEA), for example, when we communicate with you using a cloud-based service provider that operates outside the EEA such as MailChimp. Such transfers will only take place if one of the following applies:

* the country receiving the data is considered by the EU to provide an adequate level of data protection;
* the organisation receiving the data is covered by an arrangement recognised by the EU as providing an adequate standard of data protection e.g. transfers to companies that are certified under the EU US Privacy Shield;
* the transfer is governed by approved contractual clauses;
* the transfer has your consent;
* the transfer is necessary for the performance of a contract with you or to take steps requested by you prior to entering into that contract; or
* the transfer is necessary for the performance of a contract with another person, which is in your interests.

Unfortunately, the transmission of information via the internet is not completely secure. Although we will do our best to protect your personal data, we cannot guarantee the security of data transmitted to the website and any transmission is at your own risk.

## Third party websites

Our site contains links to and from various third-party websites. If you follow a link to any of these websites, please note that these websites have their own privacy policies and that we do not accept any responsibility or liability for these policies. Please check these policies before you submit any personal data to these websites.

## Retaining your data

We will only retain your data for as long as we need it to fulfil our purposes, including any relating to legal, accounting, or reporting requirements.

## Your rights

Under certain circumstances, by law you have the right to:

* Request access to your data (commonly known as a “subject access request”). This enables you to receive a copy of your data and to check that we are lawfully processing it.
* Request correction of your data. This enables you to ask us to correct any incomplete or inaccurate information we hold about you.
* Request erasure of your data. This enables you to ask us to delete or remove your data where there is no good reason for us continuing to process it. You also have the right to ask us to delete or remove your data where you have exercised your right to object to processing (see below).
* Object to processing of your data where we are relying on our legitimate interests (or those of a third party) and there is something about your particular situation which makes you want to object to processing on this ground. [You also have the right to object where we are processing your data for direct marketing purposes.]
* Request the restriction of processing of your data. This enables you to ask us to suspend the processing of your data, for example if you want us to establish its accuracy or the reason for processing it.
* Request the transfer of your data to another party.

Depending on the circumstances and the nature of your request it may not be possible for us to do what you have asked, for example, where there is a statutory or contractual requirement for us to process your data and it would not be possible to fulfil our legal obligations if we were to stop. However, where you have consented to the processing (for example, where you have asked us to contact you for marketing purposes) you can withdraw your consent at any time by emailing us at equator@csm.ox.ac.uk. In this event, we will stop the processing as soon as we can. However, this will not affect the lawfulness of any processing carried out before your withdrawal of consent and you may no longer be able to use the site in the same way as you did before.

If you want to exercise any of the rights described above or are dissatisfied with the way we have used your information, you should contact the University’s Information Compliance Team at data.protection@admin.ox.ac.uk. The same email address may be used to contact the University’s Data Protection Officer. We will seek to deal with your request without undue delay, and in any event in accordance with the requirements of the GDPR. Please note that we may keep a record of your communications to help us resolve any issues which you raise.

If you remain dissatisfied, you have the right to lodge a complaint with the Information Commissioner’s Office at https://ico.org.uk/concerns/.

## Cookie Policy

Our site uses cookies to distinguish you from other users of our site. This helps us to provide you with a good experience when you browse our site and also allows us to improve our site. For detailed information on the cookies we use and the purposes for which we use them please see the table below.

## Cookies in use on this website

Necessary cookies help make a website usable by enabling basic functions like page navigation and access to secure areas of the website. The website cannot function properly without them.

Name | Provider | Purpose | Expiry | Type
-----|----------|-------------------------|-----|-----|
CookieControl | Cookie Control | Cookie Control cookies. This cookie is set to remember the user’s preferences about cookies. | 3 Months | HTTP Cookie

Statistic cookies help website owners to understand how visitors interact with websites by collecting and reporting information anonymously.

Name | Provider | Purpose | Expiry | Type
-----|----------|-------------------------|-----|-----|
__utm.gif | Google | Google Analytics Tracking Code that logs details about the visitor’s browser and computer. | Session | Pixel Tracker
__utma | Google | Collects data on the number of times a user has visited the website as well as dates for the first and most recent visit. Used by Google Analytics. | 2 years | HTTP Cookie
__utmb | Google | Registers a timestamp with the exact time of when the user accessed the website. Used by Google Analytics to calculate the duration of a website visit. | 1 day | HTTP Cookie
__utmc | Google | Registers a timestamp with the exact time of when the user leaves the website. Used by Google Analytics to calculate the duration of a website visit. | Session | HTTP Cookie
__utmt | Google | Used to throttle the speed of requests to the server. | 1 day | HTTP Cookie
__utmv | Google | Saves user-defined tracking parameters for use in Google Analytics. | Session | HTTP Cookie
__utmz | Google | Collects data on where the user came from, what search engine was used, what link was clicked and what search term was used. Used by Google Analytics. | 6 months | HTTP Cookie

We use Oxford University's agreement with Microsoft Clarity to capture how you use and interact with our website through behavioural metrics, heatmaps, and session replay to improve and market our products/services. Website usage data is captured using first and third-party cookies and other tracking technologies to determine the popularity of products/services and online activity. Additionally, we use this information for site optimization, fraud/security purposes, and advertising. For more information about how Microsoft collects and uses your data, visit the [Microsoft Privacy Statement](https://www.microsoft.com/privacy/privacystatement).

## Changes to this policy

Any changes we may make to our privacy policy in the future will be posted on this page. Please check back frequently to see any updates or changes to our privacy policy.

## Contact

If you wish to raise any queries or concerns about this privacy policy, please contact us at equator@csm.ox.ac.uk.