title: "CONSORT reporting guideline for writing clinical trial research articles"
acronym: CONSORT
acronym-definition: ''
journal-endorsement-count: 500+
id: consort
doi-for-citation-count: 10.1186/1741-7015-8-18
# data-repo: jamesrharwood/consort
open-e-and-e: true
version: '1.1'


