---
title: "Discussion for SRQR item: [Data collection methods](..)"
citation: false
---
::: {.grid id="data-collection-methods"}
::: {.g-col-9}
#### Data collection methods
:::
::: {.g-col-3}
:::
:::

Describe <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem5" aria-controls="offcanvasExample" role="button">data collection methods</span> and design in detail, and justify them in relation to the research question(s), paradigm, <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem4" aria-controls="offcanvasExample" role="button">approach</span>, and other methods.^[Researchers may choose to use information from multiple sources, contexts, and/or time points depending on their approach and research question(s). (See [Item 11](./#data-collection-instruments-and-technologies) for triangulation.)]

<!-- #TODO is triangulation a requirement, or part of definition of data collection methods? Isn't it in item 11 again? -->

If data collection and analysis was iterative:

* describe the iterative process

* if changes occurred during the research process, describe how and why study procedures changed in response to evolving study findings.

Identify the study period.

Describe important characteristics of the individuals conducting interviews, observations or focus groups, and methods used to train these individuals.

::: {#data-collection-methods-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Examples

Jump to:

* [Why readers need this information](#sec-data-collection-methods-2)
* [Examples](#sec-data-collection-methods-3)


## Why readers need this information{#sec-data-collection-methods-2}

The <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem7" aria-controls="offcanvasExample" role="button">study period</span> helps readers place the study in temporal context and identify factors not mentioned by the authors that might affect findings, interpretation, and implications. (See Item 8 for ending data collection.)

<!-- #ASK: why is item 8 relevant? -->

Describing researcher characteristics clarifies the relationship between the individuals involved in data collection and the participants in the research and also explains what efforts were made to ensure consistency in the data collection process (See Items 6 and 15.)

<!-- #ASK: does it? This is framed as justification but maybe it's instruction of what to write? Why do readers need this? -->

<!-- #ASK: This isn't in the subheading: **Types of data collected; details of data collection procedures including (as appropriate) start and stop dates of data collection and analysis, <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem6" aria-controls="offcanvasExample" role="button">iterative</span> process, triangulation of sources/methods, and modification of procedures in response to evolving study findings; rationale.** -->

## Examples{#sec-data-collection-methods-3}

> Further, it was decided that group interviews, also known as focus group discussions would be the best means of data collection. This is a method of data collection that enables group members to feed off each other's ideas and an effective moderator will maintain group focus whilst at the same time permitting flexibility in the direction those aspects of the discussion might take. [REF]

> Adjustments to the interview protocol were made according to early experience and information participants had provided (i.e. redundant questions were eliminated; questions were reworded to improve flow and clarity; additional probes were included).

> Faculty staff were then interviewed individually by a trained study investigator in a 15-minute, semi-structured interview. This sequence was repeated with other video encounters. Table 2 presents examples of interview questions. Each faculty member was interviewed by at least three interviewers over their various interviews. Interviewers were chosen based on their experience in interviewing. All were trained during a half-day meeting to interpret and deliver the interview guide in the same manner in order to elicit information of a consistent type.

[Back to top](#data-collection-methods)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Data collection methods"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
