---
title: "Discussion for SRQR item: [Integration with prior work, implications, transferability, and contribution(s) to the field](..)"
citation: false
---
::: {.grid id="integration-with-prior-work"}
::: {.g-col-9}
#### Integration with prior work, implications, transferability, and contribution(s) to the field
:::
::: {.g-col-3}
:::
:::

Describe how the findings and conclusions connect to, support, elaborate on, or challenge previous findings, experiences, theory, or a guiding paradigm or <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem4" aria-controls="offcanvasExample" role="button">approach</span>.^[The discussion provides authors an opportunity to elaborate on their findings in relation to their research question(s) and study purpose(s); connect their findings to prior empirical work, theories, and/or frameworks; and discuss implications.]

Describe how the findings contribute to or advance the field.

Describe any implications of the work, such transferability or generalizability.

<!-- #ASK transferability vs generalizability? -->

::: {#integration-with-prior-work-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Examples

Jump to:

* [Why readers need this information](#sec-integration-with-prior-work-2)
* [Examples](#sec-integration-with-prior-work-3)


## Why readers need this information{#sec-integration-with-prior-work-2}

The short summary reminds readers of the main findings and may help them assess whether the subsequent interpretation and implications formulated by the authors are supported by the findings.

## Examples{#sec-integration-with-prior-work-3}

> This study contributes to the understanding and discussion of the complexity of involving patients in healthcare education. It shows that integrating patient-led teaching into initiatives that are partly faculty-led influences the way in which students perceive learning from and with PIs. What is not known, however, is whether perceptions are also affected by type of health profession and the students’ different orientation towards logics of care and science, and issues of authority and power relations.

For complete examples of Discussions, see:

* [Henriksen & Ringsted, 2013](http://www.ncbi.nlm.nih.gov/pubmed/23591973)

* [Westerman et al., 2013](http://www.ncbi.nlm.nih.gov/pubmed/23488760).

[Back to top](#integration-with-prior-work)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Integration with prior work, implications, transferability, and contribution(s) to the field"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
