---
title: "Discussion for SRQR item: [Limitations](..)"
citation: false
---
::: {.grid id="limitations"}
::: {.g-col-9}
#### Limitations
:::
::: {.g-col-3}
:::
:::

Describe problems or gaps in their efforts to ensure trustworthiness and the potential implications.^[Whereas you should describe techniques used to ensure trustworthiness in the Methods section of the manuscript, this section is about the gaps that you didn't or couldn't cover. For example, if you intended to interview individuals with certain characteristics, or who might offer different perspectives, but were unsuccessful in recruiting any willing participants, explain this issue and describe possible consequences for transferability. (See also Item 18.)] ["Authors should never feel nervous to report limitations. In fact, thoughtful discussion of limitations is a hallmark of good research!"[Charles Ruggle - Editor]{.attribution}]{.aside}

Describe how the chosen paradigm, approach, and methods will influence the situations to which the findings may reasonably apply.^[All research paradigms and approaches have strengths and weaknesses.] (See also [Item 18](./#integration-with-prior-work-implications-transferability-and-contributions-to-the-field).)

Describe how specific decisions or events in the conduct of the study strengthen or weaken the rigor of the findings.

::: {#limitations-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Example

Jump to:

* [Why readers need this information](#sec-limitations-2)
* [Example](#sec-limitations-3)


## Why readers need this information{#sec-limitations-2}

All research has limitations. Discussing them will help readers consider the relevance to their context and the resonance with their own experience or observations (or lack of resonance and why that might be). If you don't address limitations, editors and peer reviewers may ask you about them which will delay publication.

## Example{#sec-limitations-3}

> The study has several limitations. One is that the focus group interview method reveals students’ perceptions rather than their actual behaviors. Observations of the patient-led teaching encounter may have illuminated an understanding of the relationship between patient instructors and medical students. Another limitation is that the PI-led teaching is optional rather than mandatory, which may have influenced students’ attitudes in a positive direction. Moreover, students who are eager to take on extra-curricular activities may not be representative of the whole population. That only 23 out of 39 students signed up for this study might also have influenced results if the missing group of students represented other perceptions than those present in the focus groups. However the received data from the focus groups were rich in information and diverse perceptions were present. Another limitation is the overrepresentation of women over men in our sample. Even though women are also overrepresented in medical school this might potentially have influenced results, but gender differences in perceptions were nevertheless not identified in the data.

[Back to top](#limitations)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Limitations"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
