---
title: "Discussion for SRQR item: [Links to empirical data](..)"
citation: false
---
::: {.grid id="links-to-empirical-data"}
::: {.g-col-9}
#### Links to empirical data
:::
::: {.g-col-3}
:::
:::

Provide evidence (e.g., quotes, field notes, text excerpts, photographs) to substantiate the more general and abstract concepts or inferences they present as findings.^[Evidence is typically de-identified to protect the privacy of study participants, settings, and/or institutions.] ["I love seeing evidence like this because it really brings results to life." [Nkinda Akaro - Researcher]{.attribution}]{.aside}

You could report this evidence in a table or figure, incorporated into a narrative description of findings, as a stand-alone narrative, or in text blocks embedded in the manuscript text. If you are constrained by word limits or media limitations (e.g.. video), consider sharing data via  an appendix, supplemental material, or web-based repository.

::: {#links-to-empirical-data-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Examples

Jump to:

* [Why readers need this information](#sec-links-to-empirical-data-2)
* [Examples](#sec-links-to-empirical-data-3)


## Why readers need this information{#sec-links-to-empirical-data-2}

This information helps readers know what decisions the researchers made and why so the reader can 1) consider the relevance to their context and the resonance with their own experience or observations (or lack of resonance and why that might be) and 2) evaluate or critically appraise the manuscript.

<!-- #ASK Doesn't really reflect necessity -->

## Examples{#sec-links-to-empirical-data-3}

See Frankel et al. for an excellent example of how to use photographs (or snapshots from video) to illustrate and provide supporting evidence for patterns of behavior identified in the analysis. [http://qualitysafety.bmj.com/content/21/Suppl_1/i121](http://qualitysafety.bmj.com/content/21/Suppl_1/i121).

> We identified five interruption types: (1) probing for further data, (2) prompting for expected sequence, (3) teaching around the case, (4) thinking out loud, and (5) providing direction (see Table 1). Several interruption types served both goals of the case review discussions—teaching and patient care. For example, when thinking out loud, supervisors reasoned through problems and taught the team: “So that’s the big question, did she have a mechanical fall, or did she have a medicine-related fall?” (Case 2). Supervisors prompted for expected sequence, preventing presenters from skipping over information while simultaneously allowing the supervisor to instruct the team on presentation style: “So now you can tell me what the rest of his test results are because I haven’t heard those” (Case 16).

[Back to top](#links-to-empirical-data)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Links to empirical data"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
