---
title: "Discussion for SRQR item: [Sampling strategy](..)"
citation: false
---
::: {.grid id="sampling-strategy"}
::: {.g-col-9}
#### Sampling strategy
:::
::: {.g-col-3}
:::
:::

Describe how and why research participants, sites, documents/artifacts, and/or events were selected for inclusion in (and, if appropriate, exclusion from) the study, along with a justification for this strategy.

Describe the <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem3" aria-controls="offcanvasExample" role="button">sampling strategy</span> rather than simply labeling it (e.g., "purposive" or "snowball"), since such labels do not have a universally accepted definition and, more importantly, procedures tend to be study- specific.

<!-- #TODO: null case for <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem3" aria-controls="offcanvasExample" role="button">sampling strategy</span> -->

Describe how you established the final sample size:

* If you used a flexible <span class="defined" data-bs-toggle="offcanvas" href="#glossaryItem3" aria-controls="offcanvasExample" role="button">sampling strategy</span>, then explain the criteria used to decide when no further sampling was necessary.

* If data collection ended once saturation or sufficiency had been reached, then describe the specific criteria used to define saturation or sufficiency.

<!-- #TODO: null case for sample size-->

<!-- #TODO definition of sampling implies design judgement  -->

Describe procedures used to recruit participants, including:

* who was involved in recruitment

* what their relationship was to participants

* how and when recruitment occurred

* why these procedures were selected. (See also [Item 6: Researcher characteristics and reflexivity](./#researcher-characteristics-and-reflexivity))

::: {#sampling-strategy-collapsible .callout-note appearance="minimal" collapse=true}

## Justification and Examples

Jump to:

* [Why readers need this information](#sec-sampling-strategy-2)
* [Examples](#sec-sampling-strategy-3)


## Why readers need this information{#sec-sampling-strategy-2}

This information helps readers understand the source of data / findings so they can consider the boundaries of the study and the relevance to their own context. It also gives readers insight into the researchers' decisions, which can be important for critical appraisal.

## Examples{#sec-sampling-strategy-3}

> As students’ perceptions were previously shown to be related to gender, age, prior experience and place of attachment,[REF] we purposely selected respondents with different backgrounds. This sampling strategy led to the diversity of gender, age, prior patient experience and place of attachment shown in Table 1.

> Purposive sampling was directed towards achieving maximum variation in age and specialty, using a snowball approach (‘a non-probabilistic form of sampling in which persons initially chosen for the sample are used as informants to locate other persons having necessary characteristics making them eligible for the sample’).[REF ]

> Potential participants were all medical students in Years 1 and 2 at the University of Toronto in 2004. Following research ethics board approval, recruitment was conducted via e-mail to class listservs. Participant responses were sent directly to the research assistant, who was unknown to participants, so that the principal investigators did not know who did or did not participate. This process was engaged to protect participants’ anonymity and to avoid any impression of coercion because the lead researcher (SG) was involved in the administration of the undergraduate curriculum at the time. Sample size was estimated to be sufficient based on the principle of theoretical saturation [REF] and our previous experience with this methodology (i.e., with a relatively homogeneous population, we expected to reach saturation with approximately 15 interviews per group). There were no exclusion criteria and we accepted the first 15 students from each class who volunteered.

[Back to top](#sampling-strategy)
:::

<script src="https://giscus.app/client.js"
data-repo="jamesrharwood/srqr"
data-repo-id="R_kgDOIaTtVw"
data-category="Announcements"
data-category-id="DIC_kwDOIaTtV84CSe8S"
data-mapping="specific"
data-term="Sampling strategy"
data-strict="0"
data-reactions-enabled="1"
data-emit-metadata="0"
data-theme="preferred_color_scheme"
data-theme="light"
data-lang="en"
crossorigin="anonymous"
async>
</script>
