local_backend: true
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "assets/images" # Media files will be stored in the repo under images/uploads
collections:
  - label: Pages
    name: pages
    delete: false
    extension: markdown
    files: 
      - label: index123
        name: Home Page
        file: /index.qmd
        fields: 
          - label: 'Page title'
            name: pagetitle
            widget: string
          - label: 'Body'
            name: body
            widget: markdown
