

::: {.hero-banner}
::: {.content-block}
::: {.section}

{{< include partials/why_use.md >}}

::: {.citations-counter}
<span class="__dimensions_badge_embed__ badge-inline" data-doi=10.1097/ACM.0000000000000388 data-legend="never" data-style="large_rectangle"></span>
<span type="button" class="badge-inline btn btn-sm journal-endorsement">Journal endorsements</span>
<span class="journal-endorsement journal-endorsement-count">{{< meta journal-endorsement-count >}}</span>
<script async src="https://badge.dimensions.ai/badge.js" charset="utf-8"></script>
:::
:::{.text-small}
{{< meta acronym >}}: {{< meta full-title >}}

{{< meta translations >}}

Version: This is the latest version
:::
:::
:::
:::


## How to use this guideline 

You can use <span class="defined" data-bs-toggle="offcanvas" href="#reportingGuidelines" aria-controls="offcanvasExample" role="button">reporting guidelines</span> throughout your research process. 

* When writing: Consider using a [writing guide](#downloads) to draft your manuscript or protocol.
* After writing: Complete a [checklist](#downloads) and include it with your journal submission.
* To learn: Consult the [guidance](#summary) whenever you need it.

Please [cite](#citation) SRQR, however you use it.

::: {.grid #downloads}
::: { .g-col-12 .g-col-md-4}
<a href="#summary"><button type="button" class="btn btn-primary btn-action btn-lg width-100">Full Guidance</button></a>
:::

::: { .g-col-12 .g-col-md-4}
<a href="./srqr_writing_guide.docx"><button type="button" class="btn btn-primary btn-action btn-lg width-100">Writing Guide</button></a>
:::

::: { .g-col-12 .g-col-md-4}
<a href="./srqr_checklist.docx"><button type="button" class="btn btn-primary btn-action btn-lg width-100">Checklist</button></a>
:::
:::



## Applicability criteria

::: {.callout-tip icon=false appearance="simple"}
{{< include partials/use_for.md >}}
:::


::: {.callout-warning icon=false appearance="simple"}
{{< include partials/not_use_for.md >}}
:::

::: {.callout-note icon=false appearance="simple"}
{{< include partials/related_resources.md >}}
:::

{{< include partials/item_order.md >}}




## How this reporting guideline was made

{{< meta acronym >}} was made through a rigorous, evidence based process and originally published as an [academic article]({{< meta articles.development >}}). The UK EQUATOR Centre then worked with SRQR's developers to make it easier to use by clarifying language, adding definitions, examples, extra information and resources. Although worded differently, the guidance on this website is conceptually the same as the original publication and can be used interchangeably. Read more about [SRQR's development](./faq#development) in the FAQ.


{{< include partials/how_to_cite.md >}}

## Ready to get started? {.unnumbered .unlisted}

<a href="#how-to-use-this-guideline"><button type="button" class="btn btn-primary btn-lg width-100">Download resources</button></a>

{{< include partials/glossary_offcanvas.html >}}

