---
title: Introduction to reporting guideline checklists
---

You can use reporting checklists to demonstrate to editors, peer reviewers, and readers that your manuscript adheres to reporting guidelines. 

## #TODO - introduce reporting checklists 

To address:

    - A statement about how this means it'll be transparent/impactful/findable/useful.
    - Also act as useful summaries
    - RGs are best used early, but if drafting a manuscript, application, or protocol, you should consider using a writing guide instead.
    - How to use a reporting checklist
    - How to complete one
    - How to show where content is (options such as page and paragraph numbers)
    - What to do if you didn't do something 
    - What to write if you couldn't do something
    - Getting colleagues to double check your work
    - Make sure you consult the full guidance too
    - Link to relevant training
    - Notes to editors about how to enforce reporting checklists at their journal
    - Notes to peer reviewers about how to use checklists / when to use them / when _not_ to use them